modules_dir = "artifacts/"

[[module]]
    name = "local_storage"
    logger_enabled = true

[[module]]
    name = "curl_adapter"
    # logger_enabled = false

    [module.mounted_binaries]
    curl = "/usr/bin/curl"

[[module]]
    name = "facade"
    # logger_enabled = true
